Repository jung-dam-diary/team-angelbaby-jungdam-be, pull requests merged in 2021-12, with the labels that each got.

#2 :construction_worker: [Feature/cicd-1] CI / CD 시스템 적용
  .github/workflows/gradle.yml
  Dockerfile
  appspec.yml
  scripts/afterInstall.sh
  scripts/beforeInstall.sh
  src/main/java/com/jungdam/AppController.java
Labels: feature

#3 :construction_worker: [Develop] CI / CD 시스템 적용
  .github/workflows/gradle.yml
  Dockerfile
  appspec.yml
  scripts/afterInstall.sh
  scripts/beforeInstall.sh
  src/main/java/com/jungdam/AppController.java
Labels: feature

#5 :green_heart: [Feature/cicd-4] docker pull 과정 image 네임 오타
  scripts/afterInstall.sh
Labels: refactor

#10 :green_heart: [Feature/cicd-6] event trigger pull request 제거
  .github/workflows/gradle.yml
Labels: fix

#15 :wrench: [Feature/config-14] 로컬 개발 환경 설정
  docker-compose.yml
  src/main/resources/application.yaml
Labels: feature

#18 :sparkles: [Feature/domain-13] 전체 Entity 구현
  src/main/java/com/jungdam/album/domain/Album.java
  src/main/java/com/jungdam/album/domain/vo/Diaries.java
  src/main/java/com/jungdam/album/domain/vo/Invitations.java
  src/main/java/com/jungdam/album/domain/vo/Participants.java
  src/main/java/com/jungdam/comment/domain/Comment.java
  src/main/java/com/jungdam/common/domain/BaseEntity.java
  src/main/java/com/jungdam/diary/domain/Diary.java
  src/main/java/com/jungdam/diary/domain/vo/Comments.java
  src/main/java/com/jungdam/diary/domain/vo/DiaryPhotos.java
  src/main/java/com/jungdam/diary/domain/vo/Emojis.java
  src/main/java/com/jungdam/diary_image/domain/DiaryPhoto.java
  src/main/java/com/jungdam/emoji/domain/Emoji.java
  src/main/java/com/jungdam/invitation/domain/Invitation.java
  src/main/java/com/jungdam/invitation/domain/vo/Status.java
  src/main/java/com/jungdam/member/domain/Member.java
  src/main/java/com/jungdam/member/domain/vo/.gitignore
  src/main/java/com/jungdam/member/domain/vo/Role.java
  src/main/java/com/jungdam/member/domain/vo/Status.java
  src/main/java/com/jungdam/participant/domain/Participant.java
  src/main/java/com/jungdam/participant/domain/vo/Role.java
  src/main/resources/banner.txt
Labels: feature

#20 💚 [Feature/cicd-19] build 과정 버그 수정
  .github/workflows/gradle.yml
Labels: fix

#22 :bug: [Fix/cicd-21] submodule .gitmodules 파일 없어짐!
  .github/workflows/gradle.yml
  .gitmodules
Labels: fix

#24 🐛 [Feature/GitHub-23] PR 템플릿 Gitmoji 수정
  .github/PULL_REQUEST_TEMPLATE.md
Labels: fix

#28 ♻️ [Feature/Domain-27] Domain Vo Wrapping 진행
  src/main/java/com/jungdam/album/domain/Album.java
  src/main/java/com/jungdam/album/domain/vo/FamilyMotto.java
  src/main/java/com/jungdam/album/domain/vo/Thumbnail.java
  src/main/java/com/jungdam/album/domain/vo/Title.java
  src/main/java/com/jungdam/comment/domain/Comment.java
  src/main/java/com/jungdam/comment/domain/vo/Content.java
  src/main/java/com/jungdam/common/dto/ResponseDto.java
  src/main/java/com/jungdam/diary/domain/Diary.java
  src/main/java/com/jungdam/diary/domain/vo/Bookmark.java
  src/main/java/com/jungdam/diary/domain/vo/Content.java
  src/main/java/com/jungdam/diary/domain/vo/RecordedAt.java
  src/main/java/com/jungdam/diary/domain/vo/Title.java
  src/main/java/com/jungdam/diary_image/domain/DiaryPhoto.java
  src/main/java/com/jungdam/diary_image/domain/vo/Image.java
  src/main/java/com/jungdam/emoji/domain/Emoji.java
  src/main/java/com/jungdam/emoji/domain/vo/Content.java
Labels: feature

#49 🐛 [Fix/cicd-48] github actions config 파일 이름 변경해야함
  .github/workflows/gradle.yml
Labels: fix

#53 ✨ [Feature/image-29] AWS S3 이미지 업로드 기능
  build.gradle
  src/main/java/com/jungdam/common/dto/ResponseMessage.java
  src/main/java/com/jungdam/config/AmazonS3Config.java
  src/main/java/com/jungdam/error/ErrorMessage.java
  src/main/java/com/jungdam/error/exception/FileConverterException.java
  src/main/java/com/jungdam/image/application/S3Uploader.java
  src/main/java/com/jungdam/image/dto/bundle/UploadBundle.java
  src/main/java/com/jungdam/image/dto/response/UploadResponse.java
  src/main/java/com/jungdam/image/presentation/ImageController.java
Labels: feature

#55 :bug: [Fix/image-54] test code 오류 수정
  src/test/java/com/jungdam/JungdamApplicationTests.java
Labels: fix

#57 ♻️[Refactor/member-56] Member 도메인 및 Security 수정
  src/main/java/com/jungdam/AppController.java
  src/main/java/com/jungdam/auth/application/CustomOAuth2UserService.java
  src/main/java/com/jungdam/auth/application/CustomUserDetailsService.java
  src/main/java/com/jungdam/auth/domain/AuthPrincipal.java
  src/main/java/com/jungdam/auth/dto/request/AuthRequestDto.java
  src/main/java/com/jungdam/auth/filter/TokenAuthenticationFilter.java
  src/main/java/com/jungdam/auth/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/jungdam/auth/handler/RestAuthenticationEntryPoint.java
  src/main/java/com/jungdam/auth/handler/TokenAccessDeniedHandler.java
  src/main/java/com/jungdam/auth/presentation/AuthController.java
  src/main/java/com/jungdam/auth/token/AuthToken.java
  src/main/java/com/jungdam/auth/token/AuthTokenProvider.java
  src/main/java/com/jungdam/common/config/AmazonS3Config.java
  src/main/java/com/jungdam/common/config/PropertiesConfig.java
  src/main/java/com/jungdam/common/config/SecurityConfig.java
  src/main/java/com/jungdam/common/dto/ResponseDto.java
  src/main/java/com/jungdam/common/properties/AuthProperties.java
  src/main/java/com/jungdam/common/properties/CorsProperties.java
  src/main/java/com/jungdam/common/utils/SecurityUtils.java
  src/main/java/com/jungdam/error/ErrorResponseDto.java
  src/main/java/com/jungdam/error/GlobalExceptionHandler.java
  src/main/java/com/jungdam/image/presentation/ImageController.java
  src/main/java/com/jungdam/member/application/MemberRefreshTokenService.java
  src/main/java/com/jungdam/member/application/MemberService.java
  src/main/java/com/jungdam/member/domain/Member.java
  src/main/java/com/jungdam/member/domain/MemberRefreshToken.java
  src/main/java/com/jungdam/member/domain/vo/Avatar.java
  src/main/java/com/jungdam/member/domain/vo/Email.java
  src/main/java/com/jungdam/member/domain/vo/Password.java
  src/main/java/com/jungdam/member/dto/MemberBundle.java
  src/main/java/com/jungdam/member/dto/MemberResponse.java
  src/main/java/com/jungdam/member/dto/bundle/ReadMemberBundle.java
  src/main/java/com/jungdam/member/dto/response/ReadMemberResponse.java
  src/main/java/com/jungdam/member/infrastructure/MemberRepository.java
  src/main/java/com/jungdam/member/presentation/MemberController.java
Labels: refactor

#60 🚑️[Hotfix/member-59] OAuth2 Member Builder 수정
  src/main/java/com/jungdam/auth/application/CustomOAuth2UserService.java
Labels: fix

#74 ✨ [Feature/invitation-41] Invitation 초대 기능 구현
  src/main/java/com/jungdam/common/dto/ResponseMessage.java
  src/main/java/com/jungdam/error/ErrorMessage.java
  src/main/java/com/jungdam/invitation/application/InvitationService.java
  src/main/java/com/jungdam/invitation/converter/InvitationConverter.java
  src/main/java/com/jungdam/invitation/domain/Invitation.java
  src/main/java/com/jungdam/invitation/dto/bundle/CreateInvitationBundle.java
  src/main/java/com/jungdam/invitation/dto/request/CreateInvitationRequest.java
  src/main/java/com/jungdam/invitation/dto/response/CreateInvitationResponse.java
  src/main/java/com/jungdam/invitation/facade/InvitationFacade.java
  src/main/java/com/jungdam/invitation/infrastructure/InvitationRepository.java
  src/main/java/com/jungdam/invitation/presentation/InvitationController.java
Labels: feature

#67 ✨[Feature/diary-66] 일기 상세정보 조회
  src/main/java/com/jungdam/album/application/AlbumService.java
  src/main/java/com/jungdam/album/domain/Album.java
  src/main/java/com/jungdam/album/domain/vo/FamilyMotto.java
  src/main/java/com/jungdam/album/domain/vo/Thumbnail.java
  src/main/java/com/jungdam/album/domain/vo/Title.java
  src/main/java/com/jungdam/auth/application/CustomOAuth2UserService.java
  src/main/java/com/jungdam/auth/domain/AuthPrincipal.java
  src/main/java/com/jungdam/auth/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/jungdam/auth/oauth2/OAuth2MemberInfoFactory.java
  src/main/java/com/jungdam/auth/presentation/AuthController.java
  src/main/java/com/jungdam/auth/token/AuthTokenProvider.java
  src/main/java/com/jungdam/comment/domain/Comment.java
  src/main/java/com/jungdam/comment/domain/vo/Content.java
  src/main/java/com/jungdam/common/dto/ResponseMessage.java
  src/main/java/com/jungdam/diary/application/DiaryService.java
  src/main/java/com/jungdam/diary/convert/DiaryConverter.java
  src/main/java/com/jungdam/diary/domain/Diary.java
  src/main/java/com/jungdam/diary/domain/vo/Bookmark.java
  src/main/java/com/jungdam/diary/domain/vo/Content.java
  src/main/java/com/jungdam/diary/domain/vo/DiaryPhotos.java
  src/main/java/com/jungdam/diary/domain/vo/RecordedAt.java
  src/main/java/com/jungdam/diary/domain/vo/Title.java
  src/main/java/com/jungdam/diary/dto/bundle/ReadDiaryBundle.java
  src/main/java/com/jungdam/diary/dto/request/CreateDiaryRequest.java
  src/main/java/com/jungdam/diary/dto/response/ReadDiaryResponse.java
  src/main/java/com/jungdam/diary/facade/DiaryFacade.java
  src/main/java/com/jungdam/diary/infrastructure/DiaryRepository.java
  src/main/java/com/jungdam/diary/presentation/DiaryController.java
  src/main/java/com/jungdam/diary_photo/domain/DiaryPhoto.java
  src/main/java/com/jungdam/diary_photo/domain/application/DiaryPhotoService.java
  src/main/java/com/jungdam/diary_photo/domain/vo/Image.java
  src/main/java/com/jungdam/emoji/domain/Emoji.java
  src/main/java/com/jungdam/emoji/domain/vo/Content.java
  src/main/java/com/jungdam/error/ErrorMessage.java
  src/main/java/com/jungdam/image/application/S3Uploader.java
  src/main/java/com/jungdam/image/dto/bundle/UploadBundle.java
  src/main/java/com/jungdam/image/dto/response/UploadResponse.java
  src/main/java/com/jungdam/image/presentation/ImageController.java
  src/main/java/com/jungdam/member/application/MemberService.java
  src/main/java/com/jungdam/member/converter/MemberConverter.java
  src/main/java/com/jungdam/member/domain/Member.java
  src/main/java/com/jungdam/member/domain/MemberRefreshToken.java
  src/main/java/com/jungdam/member/domain/vo/Avatar.java
  src/main/java/com/jungdam/member/domain/vo/Email.java
  src/main/java/com/jungdam/member/domain/vo/Nickname.java
  src/main/java/com/jungdam/member/dto/response/ReadMemberResponse.java
  src/main/java/com/jungdam/participant/application/ParticipantService.java
Labels: feature

#79 🐛 [Fix/participant-78] 미수정된 로직 수정
  src/main/java/com/jungdam/invitation/facade/InvitationFacade.java
Labels: fix

#80 ✨ [Feature/album-11] 앨범 생성 기능 구현
  src/main/java/com/jungdam/album/application/AlbumService.java
  src/main/java/com/jungdam/album/converter/AlbumConverter.java
  src/main/java/com/jungdam/album/domain/Album.java
  src/main/java/com/jungdam/album/domain/vo/FamilyMotto.java
  src/main/java/com/jungdam/album/domain/vo/Thumbnail.java
  src/main/java/com/jungdam/album/domain/vo/Title.java
  src/main/java/com/jungdam/album/dto/bundle/CreateAlbumBundle.java
  src/main/java/com/jungdam/album/dto/request/CreateAlbumRequest.java
  src/main/java/com/jungdam/album/dto/response/CreateAlbumResponse.java
  src/main/java/com/jungdam/album/facade/AlbumFacade.java
  src/main/java/com/jungdam/album/infrastructure/AlbumRepository.java
  src/main/java/com/jungdam/album/presentation/AlbumController.java
  src/main/java/com/jungdam/common/dto/ResponseMessage.java
  src/main/java/com/jungdam/error/ErrorMessage.java
  src/main/java/com/jungdam/participant/domain/Participant.java
Labels: feature

#87 🐛 [Fix/config-84] Security Config 수정
  src/main/java/com/jungdam/common/config/SecurityConfig.java
Labels: fix

#83 ✨ [Feature/comment-68] 댓글 작성 기능 구현
  src/main/java/com/jungdam/comment/application/CommentService.java
  src/main/java/com/jungdam/comment/converter/CommentConverter.java
  src/main/java/com/jungdam/comment/domain/Comment.java
  src/main/java/com/jungdam/comment/domain/vo/Content.java
  src/main/java/com/jungdam/comment/dto/bundle/CreateCommentBundle.java
  src/main/java/com/jungdam/comment/dto/request/CreateCommentRequest.java
  src/main/java/com/jungdam/comment/dto/response/CreateCommentResponse.java
  src/main/java/com/jungdam/comment/facade/CommentFacade.java
  src/main/java/com/jungdam/comment/infrastructure/CommentRepository.java
  src/main/java/com/jungdam/comment/presentation/CommentController.java
  src/main/java/com/jungdam/common/config/SecurityConfig.java
  src/main/java/com/jungdam/common/dto/ResponseMessage.java
  src/main/java/com/jungdam/diary/domain/vo/Title.java
  src/main/java/com/jungdam/diary/dto/bundle/CreateDiaryBundle.java
  src/main/java/com/jungdam/diary/facade/DiaryFacade.java
  src/main/java/com/jungdam/diary/presentation/DiaryController.java
  src/main/java/com/jungdam/diary_photo/domain/vo/Image.java
  src/main/java/com/jungdam/error/ErrorMessage.java
  src/main/java/com/jungdam/invitation/presentation/InvitationController.java
  src/main/java/com/jungdam/member/presentation/MemberController.java
  src/main/java/com/jungdam/participant/application/ParticipantService.java
Labels: feature

#77 👔 [Feature/participant-40] 멤버 리스트 조회
  src/main/java/com/jungdam/album/application/AlbumService.java
  src/main/java/com/jungdam/common/dto/ResponseMessage.java
  src/main/java/com/jungdam/image/presentation/ImageController.java
  src/main/java/com/jungdam/participant/application/ParticipantService.java
  src/main/java/com/jungdam/participant/converter/ParticipantConverter.java
  src/main/java/com/jungdam/participant/domain/Participant.java
  src/main/java/com/jungdam/participant/domain/vo/Nickname.java
  src/main/java/com/jungdam/participant/domain/vo/Role.java
  src/main/java/com/jungdam/participant/dto/bundle/ReadAllParticipantBundle.java
  src/main/java/com/jungdam/participant/dto/response/ReadAllParticipant.java
  src/main/java/com/jungdam/participant/dto/response/ReadAllParticipantResponse.java
  src/main/java/com/jungdam/participant/facade/ParticipantFacade.java
  src/main/java/com/jungdam/participant/infrastructure/ParticipantRepository.java
  src/main/java/com/jungdam/participant/presentation/ParticipantController.java
Labels: feature

#96 ✨ [Feature/album-94] 앨범 제목 및 가훈 조회
  src/main/java/com/jungdam/album/converter/AlbumConverter.java
  src/main/java/com/jungdam/album/dto/bundle/ReadOneAlbumBundle.java
  src/main/java/com/jungdam/album/dto/response/ReadOneAlbumResponse.java
  src/main/java/com/jungdam/album/facade/AlbumFacade.java
  src/main/java/com/jungdam/album/presentation/AlbumController.java
  src/main/java/com/jungdam/common/dto/ResponseMessage.java
Labels: feature

#97 ✨ [Feature/diary-92] Bookmark 기능 구현
  src/main/java/com/jungdam/common/dto/ResponseMessage.java
  src/main/java/com/jungdam/diary/convert/DiaryConverter.java
  src/main/java/com/jungdam/diary/domain/Diary.java
  src/main/java/com/jungdam/diary/domain/vo/Bookmark.java
  src/main/java/com/jungdam/diary/dto/bundle/CheckBookmarkBundle.java
  src/main/java/com/jungdam/diary/dto/bundle/CreateDiaryBundle.java
  src/main/java/com/jungdam/diary/dto/response/CheckBookmarkResponse.java
  src/main/java/com/jungdam/diary/facade/DiaryFacade.java
  src/main/java/com/jungdam/diary/presentation/DiaryController.java
Labels: feature

#99 🐛 [Fix/diary-98] 미래의 날짜에 대한 일기 생성 금지
  src/main/java/com/jungdam/diary/domain/vo/RecordedAt.java
  src/main/java/com/jungdam/error/ErrorMessage.java
Labels: fix

#104 ♻️ [Refactor/Member-103] Member Builder 수정 진행
  src/main/java/com/jungdam/auth/application/CustomOAuth2UserService.java
  src/main/java/com/jungdam/member/converter/MemberConverter.java
  src/main/java/com/jungdam/member/domain/Member.java
Labels: refactor

#95 ✨ [Feature/member-42] 그룹 초대 시 회원 검색 조회 기능 구현
  src/main/java/com/jungdam/common/dto/ResponseMessage.java
  src/main/java/com/jungdam/member/application/MemberService.java
  src/main/java/com/jungdam/member/converter/MemberConverter.java
  src/main/java/com/jungdam/member/dto/bundle/SearchMemberBundle.java
  src/main/java/com/jungdam/member/dto/response/SearchMemberResponse.java
  src/main/java/com/jungdam/member/infrastructure/MemberRepository.java
  src/main/java/com/jungdam/member/presentation/MemberController.java
Labels: feature

#100 ✨ [Feature/invitation-33] 초대 목록 조회 기능 구현
  src/main/java/com/jungdam/common/domain/BaseEntity.java
  src/main/java/com/jungdam/common/dto/ResponseMessage.java
  src/main/java/com/jungdam/invitation/application/InvitationService.java
  src/main/java/com/jungdam/invitation/converter/InvitationConverter.java
  src/main/java/com/jungdam/invitation/domain/Invitation.java
  src/main/java/com/jungdam/invitation/dto/bundle/ReadAllInvitationBundle.java
  src/main/java/com/jungdam/invitation/dto/response/ReadAllInvitationResponse.java
  src/main/java/com/jungdam/invitation/facade/InvitationFacade.java
  src/main/java/com/jungdam/invitation/infrastructure/InvitationRepository.java
  src/main/java/com/jungdam/invitation/presentation/InvitationController.java
Labels: feature

#111 ✨ [Feature/Comment-69] 댓글 삭제
  src/main/java/com/jungdam/comment/converter/CommentConverter.java
  src/main/java/com/jungdam/comment/domain/Comment.java
  src/main/java/com/jungdam/comment/dto/bundle/DeleteCommentBundle.java
  src/main/java/com/jungdam/comment/dto/response/DeleteCommentResponse.java
  src/main/java/com/jungdam/comment/facade/CommentFacade.java
  src/main/java/com/jungdam/comment/presentation/CommentController.java
  src/main/java/com/jungdam/common/dto/ResponseMessage.java
  src/main/java/com/jungdam/diary/domain/Diary.java
  src/main/java/com/jungdam/diary/domain/vo/Comments.java
  src/main/java/com/jungdam/error/ErrorMessage.java
  src/main/java/com/jungdam/member/domain/Member.java
Labels: feature

#110 ✨ [Feature/member-32] 프로필 수정 기능 구현
  src/main/java/com/jungdam/auth/application/CustomOAuth2UserService.java
  src/main/java/com/jungdam/common/dto/ResponseMessage.java
  src/main/java/com/jungdam/member/application/MemberService.java
  src/main/java/com/jungdam/member/converter/MemberConverter.java
  src/main/java/com/jungdam/member/domain/vo/Nickname.java
  src/main/java/com/jungdam/member/dto/bundle/UpdateMemberBundle.java
  src/main/java/com/jungdam/member/dto/request/UpdateMemberRequest.java
  src/main/java/com/jungdam/member/dto/response/UpdateMemberResponse.java
  src/main/java/com/jungdam/member/presentation/MemberController.java
Labels: feature

#112 ✨ [Feature/diary-70] 일기 삭제 기능
  src/main/java/com/jungdam/album/domain/Album.java
  src/main/java/com/jungdam/album/domain/vo/Diaries.java
  src/main/java/com/jungdam/common/dto/ResponseMessage.java
  src/main/java/com/jungdam/diary/convert/DiaryConverter.java
  src/main/java/com/jungdam/diary/domain/Diary.java
  src/main/java/com/jungdam/diary/domain/vo/Comments.java
  src/main/java/com/jungdam/diary/dto/bundle/DeleteDiaryBundle.java
  src/main/java/com/jungdam/diary/dto/response/DeleteDiaryResponse.java
  src/main/java/com/jungdam/diary/facade/DiaryFacade.java
  src/main/java/com/jungdam/diary/presentation/DiaryController.java
Labels: feature

#109 ✨ [Feature/album-43] 앨범 삭제 & 수정 기능 구현
  scripts/afterInstall.sh
  src/main/java/com/jungdam/album/application/AlbumService.java
  src/main/java/com/jungdam/album/converter/AlbumConverter.java
  src/main/java/com/jungdam/album/domain/Album.java
  src/main/java/com/jungdam/album/dto/bundle/DeleteAlbumBundle.java
  src/main/java/com/jungdam/album/dto/bundle/UpdateAlbumBundle.java
  src/main/java/com/jungdam/album/dto/request/UpdateAlbumRequest.java
  src/main/java/com/jungdam/album/dto/response/DeleteAlbumResponse.java
  src/main/java/com/jungdam/album/dto/response/UpdateAlbumResponse.java
  src/main/java/com/jungdam/album/facade/AlbumFacade.java
  src/main/java/com/jungdam/album/infrastructure/AlbumRepository.java
  src/main/java/com/jungdam/album/presentation/AlbumController.java
  src/main/java/com/jungdam/common/dto/ResponseMessage.java
  src/main/java/com/jungdam/error/ErrorMessage.java
  src/main/java/com/jungdam/error/exception/NoPermissionException.java
  src/main/java/com/jungdam/participant/application/ParticipantService.java
  src/main/java/com/jungdam/participant/infrastructure/ParticipantRepository.java
Labels: feature

#113 ✨ [Feature/diary-89] 특정 날짜에 일기가 작성되었는지 조회
  src/main/java/com/jungdam/album/domain/Album.java
  src/main/java/com/jungdam/album/domain/vo/Diaries.java
  src/main/java/com/jungdam/common/dto/ResponseMessage.java
  src/main/java/com/jungdam/diary/convert/DiaryConverter.java
  src/main/java/com/jungdam/diary/domain/Diary.java
  src/main/java/com/jungdam/diary/domain/vo/RecordedAt.java
  src/main/java/com/jungdam/diary/dto/bundle/CheckRecordedAtDiaryBundle.java
  src/main/java/com/jungdam/diary/dto/response/CheckRecordedAtDiaryResponse.java
  src/main/java/com/jungdam/diary/facade/DiaryFacade.java
  src/main/java/com/jungdam/diary/presentation/DiaryController.java
Labels: feature

#118 🐛 [Fix/invitation-117] 초대할 사용자 앨범에 존재 여부 검사 로직 오류 수정
  src/main/java/com/jungdam/invitation/application/InvitationService.java
  src/main/java/com/jungdam/invitation/facade/InvitationFacade.java
  src/main/java/com/jungdam/participant/application/ParticipantService.java
Labels: fix

#115 ⚡️ [Feature/invitation-34] 초대 수락/거절 기능 구현
  src/main/java/com/jungdam/common/dto/ResponseMessage.java
  src/main/java/com/jungdam/error/ErrorMessage.java
  src/main/java/com/jungdam/invitation/application/InvitationService.java
  src/main/java/com/jungdam/invitation/converter/InvitationConverter.java
  src/main/java/com/jungdam/invitation/domain/Invitation.java
  src/main/java/com/jungdam/invitation/domain/vo/Status.java
  src/main/java/com/jungdam/invitation/dto/bundle/UpdateInvitationBundle.java
  src/main/java/com/jungdam/invitation/dto/request/UpdateInvitationRequest.java
  src/main/java/com/jungdam/invitation/dto/response/UpdateInvitationResponse.java
  src/main/java/com/jungdam/invitation/facade/InvitationFacade.java
  src/main/java/com/jungdam/invitation/infrastructure/InvitationRepository.java
  src/main/java/com/jungdam/invitation/presentation/InvitationController.java
Labels: feature

#121 ✨ [Feature/participant-119] 참여인원 확인
  src/main/java/com/jungdam/common/dto/ResponseMessage.java
  src/main/java/com/jungdam/participant/application/ParticipantService.java
  src/main/java/com/jungdam/participant/converter/ParticipantConverter.java
  src/main/java/com/jungdam/participant/dto/bundle/CheckParticipantBundle.java
  src/main/java/com/jungdam/participant/dto/response/CheckParticipantResponse.java
  src/main/java/com/jungdam/participant/facade/ParticipantFacade.java
  src/main/java/com/jungdam/participant/presentation/ParticipantController.java
Labels: feature

#122 ✨ [Feature/comment-114] 댓글 수정
  src/main/java/com/jungdam/comment/converter/CommentConverter.java
  src/main/java/com/jungdam/comment/domain/Comment.java
  src/main/java/com/jungdam/comment/dto/bundle/UpdateCommentBundle.java
  src/main/java/com/jungdam/comment/dto/request/UpdateCommentRequest.java
  src/main/java/com/jungdam/comment/dto/response/UpdateCommentResponse.java
  src/main/java/com/jungdam/comment/facade/CommentFacade.java
  src/main/java/com/jungdam/comment/infrastructure/CommentRepository.java
  src/main/java/com/jungdam/comment/presentation/CommentController.java
  src/main/java/com/jungdam/common/dto/ResponseMessage.java
  src/main/java/com/jungdam/diary/domain/Diary.java
  src/main/java/com/jungdam/diary/domain/vo/Comments.java
Labels: feature

#123 ✨ [Feature/diary-71] 일기 수정
  src/main/java/com/jungdam/album/domain/Album.java
  src/main/java/com/jungdam/album/domain/vo/Diaries.java
  src/main/java/com/jungdam/common/dto/ResponseMessage.java
  src/main/java/com/jungdam/diary/converter/DiaryConverter.java
  src/main/java/com/jungdam/diary/domain/Diary.java
  src/main/java/com/jungdam/diary/domain/vo/DiaryPhotos.java
  src/main/java/com/jungdam/diary/dto/bundle/UpdateDiaryBundle.java
  src/main/java/com/jungdam/diary/dto/request/UpdateDiaryRequest.java
  src/main/java/com/jungdam/diary/dto/response/UpdateDiaryResponse.java
  src/main/java/com/jungdam/diary/facade/DiaryFacade.java
  src/main/java/com/jungdam/diary/presentation/DiaryController.java
Labels: feature

#116 ✨ [Feature/album-45] 특별한 순간 조회 기능 구현
  src/main/java/com/jungdam/album/converter/AlbumConverter.java
  src/main/java/com/jungdam/album/dto/bundle/ReadAllMomentBundle.java
  src/main/java/com/jungdam/album/dto/response/ReadAllMomentResponse.java
  src/main/java/com/jungdam/album/facade/AlbumFacade.java
  src/main/java/com/jungdam/album/presentation/AlbumController.java
  src/main/java/com/jungdam/common/dto/ResponseMessage.java
  src/main/java/com/jungdam/diary/application/DiaryService.java
  src/main/java/com/jungdam/diary/domain/vo/Bookmark.java
  src/main/java/com/jungdam/diary/infrastructure/DiaryRepository.java
Labels: feature

#125 🐛 [Fix/album-124] merge conflict 이슈 해결
  src/main/java/com/jungdam/diary/application/DiaryService.java
Labels: fix

#126 ✨ [Feature/album-30] 앨범 목록 조회 기능 구현
  src/main/java/com/jungdam/album/converter/AlbumConverter.java
  src/main/java/com/jungdam/album/dto/bundle/ReadAllAlbumBundle.java
  src/main/java/com/jungdam/album/dto/response/ReadAllAlbumResponse.java
  src/main/java/com/jungdam/album/facade/AlbumFacade.java
  src/main/java/com/jungdam/album/presentation/AlbumController.java
  src/main/java/com/jungdam/common/dto/ResponseMessage.java
  src/main/java/com/jungdam/participant/application/ParticipantService.java
  src/main/java/com/jungdam/participant/infrastructure/ParticipantRepository.java
Labels: feature

#132 🐛 [Fix/member-131] 회원 검색 조회 memberId 내려주기
  src/main/java/com/jungdam/member/converter/MemberConverter.java
  src/main/java/com/jungdam/member/dto/response/SearchMemberResponse.java
Labels: fix

#133 🐛 [Fix/invitation-130] 초대 수락 시 참여자 목록에 ALBUM_MEMBER로 추가
  src/main/java/com/jungdam/invitation/domain/Invitation.java
  src/main/java/com/jungdam/invitation/facade/InvitationFacade.java
  src/main/java/com/jungdam/participant/application/ParticipantService.java
  src/main/java/com/jungdam/participant/domain/vo/Nickname.java
  src/main/java/com/jungdam/participant/infrastructure/ParticipantRepository.java
Labels: feature

#137 ✨ [Hotfix/participant-136] 종속된 연관관계 수정 진행
  src/main/java/com/jungdam/album/domain/Album.java
  src/main/java/com/jungdam/album/domain/vo/Diaries.java
  src/main/java/com/jungdam/album/domain/vo/Participants.java
  src/main/java/com/jungdam/comment/application/CommentService.java
  src/main/java/com/jungdam/comment/converter/CommentConverter.java
  src/main/java/com/jungdam/comment/domain/Comment.java
  src/main/java/com/jungdam/comment/dto/response/ReadCommentResponse.java
  src/main/java/com/jungdam/comment/facade/CommentFacade.java
  src/main/java/com/jungdam/comment/infrastructure/CommentRepository.java
  src/main/java/com/jungdam/diary/application/DiaryService.java
  src/main/java/com/jungdam/diary/converter/DiaryConverter.java
  src/main/java/com/jungdam/diary/domain/Diary.java
  src/main/java/com/jungdam/diary/domain/vo/Comments.java
  src/main/java/com/jungdam/diary/facade/DiaryFacade.java
  src/main/java/com/jungdam/diary/infrastructure/DiaryRepository.java
  src/main/java/com/jungdam/emoji/domain/Emoji.java
  src/main/java/com/jungdam/participant/application/ParticipantService.java
  src/main/java/com/jungdam/participant/domain/Participant.java
  src/main/java/com/jungdam/participant/domain/vo/Comments.java
  src/main/java/com/jungdam/participant/domain/vo/Diaries.java
  src/main/java/com/jungdam/participant/domain/vo/Emojis.java
  src/main/java/com/jungdam/participant/infrastructure/ParticipantRepository.java
Labels: hotfix

#139 ♻️ [Refactor/diary-138] db조회 대신 비즈니스 로직 처리
  src/main/java/com/jungdam/album/domain/Album.java
  src/main/java/com/jungdam/album/domain/vo/Diaries.java
  src/main/java/com/jungdam/comment/facade/CommentFacade.java
  src/main/java/com/jungdam/diary/domain/Diary.java
  src/main/java/com/jungdam/diary/facade/DiaryFacade.java
Labels: refactor

#143 ♻️ [Refactor/comment-142] 댓글 조회 리펙토링
  src/main/java/com/jungdam/comment/application/CommentService.java
  src/main/java/com/jungdam/comment/converter/CommentConverter.java
  src/main/java/com/jungdam/comment/dto/response/ReadCommentAllResponse.java
Labels: refactor

#145 ✨ [Feature/swagger-135] Swagger 인증 처리
  src/main/java/com/jungdam/common/config/SwaggerConfig.java
Labels: feature

#147 🚑️ [Hotfix/comment-146] 댓글 생성 반환 값 수정
  src/main/java/com/jungdam/comment/converter/CommentConverter.java
  src/main/java/com/jungdam/comment/dto/response/CreateCommentResponse.java
Labels: hotfix

#148 ✨ [Feature/Participant-129] 참여자 닉네임 수정
  src/main/java/com/jungdam/common/dto/ResponseMessage.java
  src/main/java/com/jungdam/participant/converter/ParticipantConverter.java
  src/main/java/com/jungdam/participant/domain/Participant.java
  src/main/java/com/jungdam/participant/dto/bundle/UpdateNicknameParticipantBundle.java
  src/main/java/com/jungdam/participant/dto/request/UpdateNicknameParticipantRequest.java
  src/main/java/com/jungdam/participant/dto/response/UpdateNicknameParticipantResponse.java
  src/main/java/com/jungdam/participant/facade/ParticipantFacade.java
  src/main/java/com/jungdam/participant/presentation/ParticipantController.java
Labels: feature

#150 ✨ [Feature/emoji-149] 이모지 기초 인프라 구성
  src/main/java/com/jungdam/diary/domain/vo/Emojis.java
  src/main/java/com/jungdam/emoji/domain/Emoji.java
  src/main/java/com/jungdam/emoji/domain/vo/Content.java
  src/main/java/com/jungdam/error/ErrorMessage.java
Labels: feature

#152 ✨ [Feature/emoji-72] 이모지 생성 및 삭제
  src/main/java/com/jungdam/common/dto/ResponseMessage.java
  src/main/java/com/jungdam/diary/domain/Diary.java
  src/main/java/com/jungdam/diary/domain/vo/Emojis.java
  src/main/java/com/jungdam/emoji/converter/EmojiConverter.java
  src/main/java/com/jungdam/emoji/domain/Emoji.java
  src/main/java/com/jungdam/emoji/dto/bundle/CreateDeleteEmojiBundle.java
  src/main/java/com/jungdam/emoji/dto/request/CreateDeleteEmojiRequest.java
  src/main/java/com/jungdam/emoji/dto/response/CreateDeleteEmojiResponse.java
  src/main/java/com/jungdam/emoji/facade/EmojiFacade.java
  src/main/java/com/jungdam/emoji/presentation/EmojiController.java
Labels: feature

#155 🚑️ [Hotfix/comment-154] 댓글 response 수정
  src/main/java/com/jungdam/comment/converter/CommentConverter.java
  src/main/java/com/jungdam/comment/domain/Comment.java
  src/main/java/com/jungdam/comment/dto/response/ReadCommentResponse.java
  src/main/java/com/jungdam/participant/domain/Participant.java
Labels: hotfix

#158 ✨ [Feature/diary-156] 일기 Feed 구현
  src/main/java/com/jungdam/comment/application/CommentService.java
  src/main/java/com/jungdam/common/dto/ResponseMessage.java
  src/main/java/com/jungdam/diary/application/DiaryService.java
  src/main/java/com/jungdam/diary/converter/DiaryConverter.java
  src/main/java/com/jungdam/diary/domain/Diary.java
  src/main/java/com/jungdam/diary/dto/bundle/ReadAllDiaryBundle.java
  src/main/java/com/jungdam/diary/dto/response/DiaryInfoResponse.java
  src/main/java/com/jungdam/diary/dto/response/ReadAllFeedDiaryResponse.java
  src/main/java/com/jungdam/diary/dto/response/ReadDetailDiaryResponse.java
  src/main/java/com/jungdam/diary/dto/response/ReadFeedDiaryResponse.java
  src/main/java/com/jungdam/diary/facade/DiaryFacade.java
  src/main/java/com/jungdam/diary/infrastructure/DiaryRepository.java
  src/main/java/com/jungdam/diary/presentation/DiaryController.java
  src/main/java/com/jungdam/participant/dto/response/ParticipantInfoResponse.java
Labels: feature

#160 ✨ [Fix/diary-159] 일기 조회시, 일기 작성자 정보 추가
  src/main/java/com/jungdam/diary/converter/DiaryConverter.java
  src/main/java/com/jungdam/diary/dto/response/ReadDetailDiaryResponse.java
  src/main/java/com/jungdam/diary/facade/DiaryFacade.java
  src/main/java/com/jungdam/participant/dto/response/ParticipantInfosResponse.java
Labels: fix

#161 ♻️ [Refactor/auth-144] Auth 및 Member 도메인 리펙토링
  src/main/java/com/jungdam/auth/application/CustomOAuth2UserService.java
  src/main/java/com/jungdam/auth/domain/AuthPrincipal.java
  src/main/java/com/jungdam/auth/handler/OAuth2AuthenticationFailureHandler.java
  src/main/java/com/jungdam/auth/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/jungdam/auth/handler/RestAuthenticationEntryPoint.java
  src/main/java/com/jungdam/auth/presentation/AuthController.java
  src/main/java/com/jungdam/auth/token/AuthTokenProvider.java
  src/main/java/com/jungdam/common/annotation/.gitignore
  src/main/java/com/jungdam/common/aop/.gitignore
  src/main/java/com/jungdam/common/config/AmazonS3Config.java
  src/main/java/com/jungdam/common/config/SecurityConfig.java
  src/main/java/com/jungdam/error/ErrorMessage.java
  src/main/java/com/jungdam/error/exception/auth/FailAuthenticationException.java
  src/main/java/com/jungdam/error/exception/auth/InternalAuthenticationException.java
  src/main/java/com/jungdam/member/application/MemberService.java
  src/main/java/com/jungdam/member/domain/Member.java
  src/main/java/com/jungdam/member/domain/vo/Email.java
  src/main/java/com/jungdam/member/domain/vo/Nickname.java
  src/main/java/com/jungdam/member/domain/vo/ProviderType.java
  src/main/java/com/jungdam/member/presentation/MemberController.java
  src/main/resources/banner.txt
Labels: refactor

#162 🐛 [Fix/moments-157] 특별한 순간 페이지네이션 Response 수정
  src/main/java/com/jungdam/album/dto/response/ReadAllMomentResponse.java
Labels: fix

#163 ✨ [Feature/diary-127] 스토리북 더보기 조회 기능 구현
  src/main/java/com/jungdam/common/dto/ResponseMessage.java
  src/main/java/com/jungdam/diary/application/DiaryService.java
  src/main/java/com/jungdam/diary/converter/DiaryConverter.java
  src/main/java/com/jungdam/diary/domain/Diary.java
  src/main/java/com/jungdam/diary/domain/vo/DiaryPhotos.java
  src/main/java/com/jungdam/diary/dto/bundle/ReadAllStoryBookBundle.java
  src/main/java/com/jungdam/diary/dto/response/ReadAllStoryBookResponse.java
  src/main/java/com/jungdam/diary/dto/response/ReadStoryBookResponse.java
  src/main/java/com/jungdam/diary/facade/DiaryFacade.java
  src/main/java/com/jungdam/diary/infrastructure/DiaryRepository.java
  src/main/java/com/jungdam/diary/presentation/DiaryController.java
  src/main/java/com/jungdam/participant/application/ParticipantService.java
Labels: feature

#164 ♻️ [Refactor/common-105] 공통 코드 수정
  src/main/java/com/jungdam/album/application/AlbumService.java
  src/main/java/com/jungdam/album/domain/vo/Diaries.java
  src/main/java/com/jungdam/album/domain/vo/FamilyMotto.java
  src/main/java/com/jungdam/album/domain/vo/Participants.java
  src/main/java/com/jungdam/album/domain/vo/Thumbnail.java
  src/main/java/com/jungdam/album/domain/vo/Title.java
  src/main/java/com/jungdam/auth/oauth2/OAuth2MemberInfoFactory.java
  src/main/java/com/jungdam/auth/presentation/AuthController.java
  src/main/java/com/jungdam/auth/token/AuthTokenProvider.java
  src/main/java/com/jungdam/comment/domain/vo/Content.java
  src/main/java/com/jungdam/common/config/SecurityConfig.java
  src/main/java/com/jungdam/common/config/SwaggerConfig.java
  src/main/java/com/jungdam/common/dto/ResponseMessage.java
  src/main/java/com/jungdam/common/utils/SecurityUtils.java
  src/main/java/com/jungdam/diary/application/DiaryService.java
  src/main/java/com/jungdam/diary/domain/vo/Comments.java
  src/main/java/com/jungdam/diary/domain/vo/Content.java
  src/main/java/com/jungdam/diary/domain/vo/RecordedAt.java
  src/main/java/com/jungdam/diary/domain/vo/Title.java
  src/main/java/com/jungdam/diary_photo/domain/vo/Image.java
  src/main/java/com/jungdam/emoji/domain/vo/Content.java
  src/main/java/com/jungdam/error/ErrorMessage.java
  src/main/java/com/jungdam/error/exception/auth/OAuthProviderMissMatchException.java
  src/main/java/com/jungdam/error/exception/common/DuplicationException.java
  src/main/java/com/jungdam/error/exception/common/InvalidArgumentException.java
  src/main/java/com/jungdam/error/exception/common/NoPermissionException.java
  src/main/java/com/jungdam/error/exception/common/NotExistException.java
  src/main/java/com/jungdam/error/exception/s3/FileConverterException.java
  src/main/java/com/jungdam/error/exception/token/InvalidRefreshTokenException.java
  src/main/java/com/jungdam/error/exception/token/NotExpiredException.java
  src/main/java/com/jungdam/error/exception/token/TokenValidFailedException.java
  src/main/java/com/jungdam/image/application/S3Uploader.java
  src/main/java/com/jungdam/invitation/application/InvitationService.java
  src/main/java/com/jungdam/invitation/domain/vo/Status.java
  src/main/java/com/jungdam/member/application/MemberService.java
  src/main/java/com/jungdam/member/domain/vo/Nickname.java
  src/main/java/com/jungdam/member/domain/vo/ProviderType.java
  src/main/java/com/jungdam/participant/application/ParticipantService.java
  src/main/java/com/jungdam/participant/facade/ParticipantFacade.java
Labels: refactor

#169 ✨ [Feature/diary-128] 스토리북 조회 기능 구현
  src/main/java/com/jungdam/common/dto/ResponseMessage.java
  src/main/java/com/jungdam/diary/application/DiaryService.java
  src/main/java/com/jungdam/diary/converter/DiaryConverter.java
  src/main/java/com/jungdam/diary/dto/bundle/ReadGroupStoryBookBundle.java
  src/main/java/com/jungdam/diary/dto/response/ReadGroupStoryBookResponse.java
  src/main/java/com/jungdam/diary/facade/DiaryFacade.java
  src/main/java/com/jungdam/diary/presentation/DiaryController.java
  src/main/java/com/jungdam/participant/application/ParticipantService.java
Labels: feature

#170 🔨 [Fix/cicd-168] 테스트 베포 환경 메모리 제한 설정
  scripts/afterInstall.sh
Labels: fix

#172 🔨 [Fix/cicd-171] 테스트 베포 환경 메모리 제한 설정
  scripts/afterInstall.sh
Labels: fix

#174 🔨 [Fix/cicd-173] 테스트 베포 환경 메모리 제한 설정
  scripts/afterInstall.sh
Labels: fix

#176 🔨 [Fix/cicd-175] 테스트 베포 환경 메모리 제한 설정
  scripts/afterInstall.sh
Labels: fix

#177 ♻️ [Feature/diary-165] 일기 조회 최적화 진행
  src/main/java/com/jungdam/album/domain/Album.java
  src/main/java/com/jungdam/album/domain/vo/Participants.java
  src/main/java/com/jungdam/album/facade/AlbumFacade.java
  src/main/java/com/jungdam/comment/application/CommentService.java
  src/main/java/com/jungdam/comment/converter/CommentConverter.java
  src/main/java/com/jungdam/comment/facade/CommentFacade.java
  src/main/java/com/jungdam/common/config/SwaggerConfig.java
  src/main/java/com/jungdam/common/utils/PageUtil.java
  src/main/java/com/jungdam/diary/application/DiaryService.java
  src/main/java/com/jungdam/diary/converter/DiaryConverter.java
  src/main/java/com/jungdam/diary/domain/Diary.java
  src/main/java/com/jungdam/diary/domain/vo/Comments.java
  src/main/java/com/jungdam/diary/domain/vo/Content.java
  src/main/java/com/jungdam/diary/domain/vo/Emojis.java
  src/main/java/com/jungdam/diary/dto/bundle/ReadAllStoryBookBundle.java
  src/main/java/com/jungdam/diary/facade/DiaryFacade.java
  src/main/java/com/jungdam/diary/presentation/DiaryController.java
  src/main/java/com/jungdam/emoji/converter/EmojiConverter.java
  src/main/java/com/jungdam/emoji/domain/Emoji.java
  src/main/java/com/jungdam/emoji/domain/vo/Content.java
  src/main/java/com/jungdam/emoji/dto/bundle/CreateDeleteEmojiBundle.java
  src/main/java/com/jungdam/emoji/dto/request/CreateDeleteEmojiRequest.java
  src/main/java/com/jungdam/emoji/dto/response/CreateDeleteEmojiResponse.java
  src/main/java/com/jungdam/emoji/facade/EmojiFacade.java
  src/main/java/com/jungdam/emoji/presentation/EmojiController.java
  src/main/java/com/jungdam/participant/application/ParticipantService.java
  src/main/java/com/jungdam/participant/converter/ParticipantConverter.java
  src/main/java/com/jungdam/participant/domain/Participant.java
  src/main/java/com/jungdam/participant/domain/vo/Emojis.java
  src/main/java/com/jungdam/participant/facade/ParticipantFacade.java
Labels: refactor

#181 🚑️ [hotfix/diary-180] 변경사항 롤백
  src/main/java/com/jungdam/diary/facade/DiaryFacade.java
Labels: hotfix

#182 🚑️ [Hotfix/diary-179] 일기 피드 조회 수정
  src/main/java/com/jungdam/diary/converter/DiaryConverter.java
  src/main/java/com/jungdam/diary/domain/Diary.java
  src/main/java/com/jungdam/diary/domain/vo/DiaryPhotos.java
  src/main/java/com/jungdam/diary/dto/response/DiaryInfoResponse.java
  src/main/java/com/jungdam/diary/dto/response/ReadAllStoryBookResponse.java
  src/main/java/com/jungdam/diary_photo/domain/DiaryPhoto.java
  src/main/java/com/jungdam/diary_photo/dto/response/DiaryPhotosInfoResponse.java
Labels: hotfix

#183 ♻️ [Refactor/comment-167] Comment 도메인 수정 진행
  src/main/java/com/jungdam/album/domain/Album.java
  src/main/java/com/jungdam/album/domain/vo/Participants.java
  src/main/java/com/jungdam/auth/filter/TokenAuthenticationFilter.java
  src/main/java/com/jungdam/auth/handler/OAuth2AuthenticationFailureHandler.java
  src/main/java/com/jungdam/auth/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/jungdam/auth/infrastructure/OAuth2AuthorizationRequestBasedOnCookieRepository.java
  src/main/java/com/jungdam/auth/presentation/AuthController.java
  src/main/java/com/jungdam/comment/application/CommentService.java
  src/main/java/com/jungdam/comment/converter/CommentConverter.java
  src/main/java/com/jungdam/comment/domain/Comment.java
  src/main/java/com/jungdam/comment/dto/bundle/ReadCommentBundle.java
  src/main/java/com/jungdam/comment/facade/CommentFacade.java
  src/main/java/com/jungdam/comment/presentation/CommentController.java
  src/main/java/com/jungdam/common/utils/CookieUtils.java
  src/main/java/com/jungdam/common/utils/HeaderUtils.java
  src/main/java/com/jungdam/common/utils/PageUtil.java
  src/main/java/com/jungdam/common/utils/PageUtils.java
  src/main/java/com/jungdam/diary/facade/DiaryFacade.java
  src/main/java/com/jungdam/diary/presentation/DiaryController.java
  src/main/java/com/jungdam/participant/domain/Participant.java
  src/main/java/com/jungdam/participant/facade/ParticipantFacade.java
Labels: refactor

#185 🔨 [Fix/cicd-184] 테스트 베포 환경 메모리 제한 수정
  scripts/afterInstall.sh
Labels: fix

#187 🔨 [Fix/cicd-186] 프로덕션 베포 환경 메모리 제한 수정
  .github/workflows/gradle.yml
  scripts/afterInstall.sh
Labels: fix

#189 🚑️ [Hotfix/invitation-188] 앨범 초대시 참여자 정보 조회
  src/main/java/com/jungdam/album/domain/Album.java
  src/main/java/com/jungdam/invitation/facade/InvitationFacade.java
Labels: hotfix

#205 🔧 [Fix/config-204] docker 실행시 time zone 설정
  scripts/afterInstall.sh
Labels: fix

#207 🔧 [Fix/config-206] docker 실행시 time zone 설정 (Prod)
  scripts/afterInstall.sh
Labels: fix

#209 🚑️ [Hotfix/comment-208] 댓글 생성 Response 수정
  src/main/java/com/jungdam/comment/converter/CommentConverter.java
  src/main/java/com/jungdam/comment/dto/response/CreateCommentResponse.java
Labels: hotfix

#193 📝 [Docs/docs-192] README update
  README.md
  images/erd.png
  images/infra.png
Labels: docs

#211 📝 [Docs/docs-210] 변경된 사항 수정
  README.md
  images/erd.png
  images/jungdam-main.png
Labels: docs

#215 ♻️ [Refactor/participant-88] 멤버 리스트 조회 Converter 리펙토링
  src/main/java/com/jungdam/participant/converter/ParticipantConverter.java
Labels: refactor

#220 🚑️ [Hotfix/diary-217] RecordedAt 비즈니스 로직 수정
  src/main/java/com/jungdam/diary/presentation/DiaryController.java
Labels: hotfix

#227 ✨ [Feature/participant 226] 참여자 역할 조회 기능 구현
  src/main/java/com/jungdam/common/dto/ResponseMessage.java
  src/main/java/com/jungdam/participant/application/ParticipantService.java
  src/main/java/com/jungdam/participant/converter/ParticipantConverter.java
  src/main/java/com/jungdam/participant/dto/bundle/ReadParticipantRoleBundle.java
  src/main/java/com/jungdam/participant/dto/response/ReadParticipantRoleResponse.java
  src/main/java/com/jungdam/participant/facade/ParticipantFacade.java
  src/main/java/com/jungdam/participant/presentation/ParticipantController.java
Labels: feature

#232 🐛 [Fix/moment-230] 특별한 순간 RecordedAt DESC 정렬하기
  src/main/java/com/jungdam/diary/application/DiaryService.java
  src/main/java/com/jungdam/diary/infrastructure/DiaryRepository.java
Labels: fix

#235 🚑️ [Hotfix/auth-234] 카카오 Info 수정
  src/main/java/com/jungdam/auth/oauth2/impl/KakaoOAuth2MemberInfo.java
Labels: hotfix

#236 🐛 [Fix/diary-233] 스토리북 조회 정렬 날짜 기준 DESC로 변경
  src/main/java/com/jungdam/diary/application/DiaryService.java
  src/main/java/com/jungdam/diary/infrastructure/DiaryRepository.java
Labels: fix

#238 🚑️ [Hotfix/diary-231] 일기 피드 정렬 추가
  src/main/java/com/jungdam/diary/application/DiaryService.java
  src/main/java/com/jungdam/diary/infrastructure/DiaryRepository.java
Labels: hotfix

#240 🚑️ [Hotfix/diary-239] diary response 값 수정
  src/main/java/com/jungdam/diary/converter/DiaryConverter.java
  src/main/java/com/jungdam/diary/domain/Diary.java
  src/main/java/com/jungdam/diary/facade/DiaryFacade.java
Labels: hotfix

#242 🐛 [Fix/diary-237] 스토리북 더보기 조회 정렬 날짜 기준 DESC로 변경
  src/main/java/com/jungdam/common/utils/PageUtils.java
  src/main/java/com/jungdam/diary/application/DiaryService.java
  src/main/java/com/jungdam/diary/application/DiarySort.java
  src/main/java/com/jungdam/diary/facade/DiaryFacade.java
  src/main/java/com/jungdam/diary/infrastructure/DiaryRepository.java
Labels: fix

#243 Revert "🐛 [Fix/diary-237] 스토리북 더보기 조회 정렬 날짜 기준 DESC로 변경"
  src/main/java/com/jungdam/common/utils/PageUtils.java
  src/main/java/com/jungdam/diary/application/DiaryService.java
  src/main/java/com/jungdam/diary/application/DiarySort.java
  src/main/java/com/jungdam/diary/facade/DiaryFacade.java
  src/main/java/com/jungdam/diary/infrastructure/DiaryRepository.java
Labels: hotfix

#245 🚑️ [Hotfix/error-216] GlobalException 추가 진행
  src/main/java/com/jungdam/error/ErrorMessage.java
  src/main/java/com/jungdam/error/GlobalExceptionHandler.java
Labels: hotfix

#246 🐛 [Fix/member-166] Service 및 Repository 수정
  src/main/java/com/jungdam/auth/application/CustomOAuth2UserService.java
  src/main/java/com/jungdam/auth/domain/AuthPrincipal.java
  src/main/java/com/jungdam/auth/handler/OAuth2AuthenticationFailureHandler.java
  src/main/java/com/jungdam/auth/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/jungdam/auth/presentation/AuthController.java
  src/main/java/com/jungdam/auth/token/AuthTokenProvider.java
  src/main/java/com/jungdam/error/ErrorMessage.java
  src/main/java/com/jungdam/member/infrastructure/MemberRepository.java
Labels: fix

#248 🔖 Release v1.0.4
  src/main/java/com/jungdam/auth/application/CustomOAuth2UserService.java
  src/main/java/com/jungdam/auth/domain/AuthPrincipal.java
  src/main/java/com/jungdam/auth/handler/OAuth2AuthenticationFailureHandler.java
  src/main/java/com/jungdam/auth/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/jungdam/auth/presentation/AuthController.java
  src/main/java/com/jungdam/auth/token/AuthTokenProvider.java
  src/main/java/com/jungdam/error/ErrorMessage.java
  src/main/java/com/jungdam/error/GlobalExceptionHandler.java
  src/main/java/com/jungdam/member/infrastructure/MemberRepository.java
Labels: release
